#BlueJ properties. Settings in this file override "bluej.defs"
#Thu Oct 08 23:05:35 EDT 2026
blackbox.uuid=bfd10f08-1033-487d-aac9-cf1102334461
bluej.editor.stride.sidebarShowing=true
bluej.language=english
bluej.openPackage1=C\:\\Users\\fatim\\OneDrive\\Documents\\music-organizer-v1\\music-organizer-v1
bluej.recentProject0=C\:\\Users\\fatim\\OneDrive\\Documents\\music-organizer-v1\\music-organizer-v1
bluej.startWithTextEval=false
bluej.terminal.x=16
bluej.terminal.y=16
bluej.uid=aa2c7a94-64b0-47ff-a0a1-138ef38c795e
extensions.org.bluej.extensions.submitter.Submitter.settings.saslrealm=
session.numeditors.java=1
session.numeditors.kotlin=0
session.numeditors.stride=0
